### ISSUE TITLE
Some error code will cause a "Dead kernel" hint

### ISSUE THREAD

**Issue by xmduhan** [fredokun/cl-jupyter#11]
Some error code will cause a "Dead kernel" hint, But in fact kernel is not Dead.
In [*]: '(1, 2)

![image](https://cloud.githubusercontent.com/assets/4588429/10655482/b38ba172-78a7-11e5-95cf-d1fe654a1a74.png)

**Comment by fredokun** [comment]
I was very lazy in handling reader-errors ...  Now the kernel don't die so easily.  Note that the Jupyter protocol is quite resilient, when a kernel dies it tries to start it again  (please see the output of the Jupyter command).   Anyway, thank you for your tests !

**Comment by xmduhan** [comment]
It works fine! Thank you!   HaHa!
