### ISSUE TITLE
Comment on last line of code block generates reader error

### ISSUE THREAD

**Issue by mmaul** [fredokun/cl-jupyter#15]
Reader error: incomplete input (condition of type: END-OF-FILE)

Reproduce with

    (print "Something")
    ; I throw reader error

**Comment by fredokun** [comment]
Ok, I've pushed a work-around ... The problem was that I encapsulated the cell code into a progn form,  so with your example I would try to eval:

```lisp
(progn (print "Something") ; I throw reader error)
```

Now, I'm doing this:

```lisp
(progn 
  (print "Something") 
  ; I throw reader error)
```
(there's a newline added)...

That's not beautiful but it seems to solve the problem, can you confirm?
