### ISSUE TITLE
TCO disabled in cl-jupyter

### ISSUE THREAD

**Issue by ZelphirKaltstahl** [fredokun/cl-jupyter#24]
I think TCO is disabled in cl-jupyter.
If you check out this SO post: http://stackoverflow.com/questions/38954537/common-lisp-why-need-even-number-of-keyword-parameters
I've tried to run a TCOable function in the notebook, where it does not do TCO and in SBCL directly, where it does TCO for the same function.

Is there a need for not having TCO in the notebook?

**Comment by fredokun** [comment]
Hi,
Sorry I've been busy on other things lately...
You can have a look at lines 39-40 of the file `cl-jupyter.lisp`.
If you comment out the declaim maybe TCO will be enabled.
