### ISSUE TITLE
ironclad

### ISSUE THREAD

**Issue by scios** [fredokun/cl-jupyter#5]
Hello Frederic
Many thanks for this master-piece. I was using 'fishbowl' for some time as native FriCAS/Axiom kernel and tried to implement protocol 5 myself, with - needless to say - little success. Now 'cl-jupyter' worked out of the box! 
    One small issue is the following (which is easy to work around) compile error.

**resolved**

**Comment by fredokun** [comment]
glad it's resolved ... there are many more issues to come I fear...
