### ISSUE TITLE
Systemwide installation

### ISSUE THREAD

**Issue by Yurlungur** [fredokun/cl-jupyter#6]
Hi,

Thanks for writing this kernel! I'd like to use it on jupyterhub. And therefore I'd like to try and modify it so that I can install the kernel systemwide rather than on a per-user basis. Unfortunately, quick-lisp is (sanely) limited to a single user. Do you have suggestions about what changes I would need to make to install the kernel systemwide? I don't want to create a systemwide version of quicklisp as this would get hairy quickly as different users install different packages.

Thanks for your time.

**Comment by fredokun** [comment]
Hi... if you're on Unix you *can* probably setup a "cl-jupyter" user and install the quicklisp dependencies once.  Then,  you can modify the cl-jupyter.lisp  script to look for dependencies there (I already use such a tweak to make ASDF aware of the cl-jupyter system)...
But still, I would recommend installing the dependencies locally (the users can run an install script ...).

Sorry if that doesn't help (I guess it doesn't).    Note that I have still to think a  little bit more on how to ease the installation (but the way I see it, that's a common issue with jupyter kernels).

**Comment by Yurlungur** [comment]
Thanks for the reply! My eventual solution is something quite similar to your suggestion. I have created a quicklisp user, where I installed cl-jupyter and I point jupyterhub to this quicklisp installation. However, once cl-jupyter has been loaded, I ask users to load their own quicklisp installations to manage packages.

It's not an ideal solution, but it seems to work for now.
