### ISSUE TITLE
code can't be executed there is warning

### ISSUE THREAD

**Issue by xmduhan** [fredokun/cl-jupyter#9]
when I try to execute this a cell :
In [6]:
(dolist (i '(1 2 3))
　　(format t "hello"))

I get this:
; 
; compilation unit aborted
;   caught 1 fatal ERROR condition

SIMPLE-STYLE-WARNING: 
The variable I is defined but never used.
Out [6]: Nil

and the format function seems not be called, and the same can be executed with sbcl and slime.

**Comment by fredokun** [comment]
Yes, I was treating warnings as errors, mostly because of handler-case.  I've added a handler-bind for the warnings... Should work now...

**Comment by xmduhan** [comment]
It work! Thank you very much! @fredokun
